# Generated by Django 4.0.2 on 2022-02-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chatroom_alter_chat_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='send_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='delivered_time',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
    ]
