# Generated by Django 4.0.2 on 2022-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_send_time_chat_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
